/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        none: "none"
      },
      transitionProperty: {
        t: "top",
        r: "right",
        b: "bottom",
        l: "left"
      },
      spacing: {
        Mhs: '56px',
        Mps: '16px',
        Bhs: '40px',
        Bps: '14px'
      },
      fontSize: {
        Mhs: '56px',
        Mps: '18px',
        Mhs2: '48px',
        Mps2: '16px',
        Bhs: '40px',
        Bps: '14px',
        Ths: '36px',
        Tps: '16px',
        Ths2: '32px',
        Ths3: '28px',
        Tps2: '14px'
      }
    },
    screens: {
      Fours: { max: '420px' },
      Four: { max: '400px' },
      Dmd: { min: '640px' },
      Dsm: { max: '640px' },
      Fsm: { max: '500px' },
      Fmd: { min: '500px' },
      se: { max: '380px' },
      ses: { min: '580px' },
      '2xl': { min: '1535px' },
      '2xls': { max: '1535px' },
      xl: { min: '1279px' },
      lg: { min: '768px' },
      Mlg: { max: '768px' },
      Hxl: { max: '1279px' },
      Hxls: { min: '1279px' },
      TRYNOW: { min: '1037px' },
      TRYNOWs: { max: '1037px' },
      Hmd: { min: '1000px' },
      Hsm: { max: '1000px' },
      md: { min: '900px' },
      sm: { max: '900px' },
      Logosm: { max: '765px' },
      xss: { min: '480px' },
      xs: { max: '480px' },
      Sixmds: { min: '600px' },
      Sixmd: { max: '600px' },
      Bmd: { min: '770px' },
      Bsm: { max: '770px' },
      Blds: { min: '800px' },
      Bld: { max: '800px' },
      Bold: { min: '1150px' },
      Bolds: { max: '1150px' },
      Bxl: { max: '1200px' },
      Bxls: { min: '1200px' },
      Header: { min: '1300px' },
      Headers: { max: '1300px' },
      Header2: { min: '1400px' },
      Headers2: { max: '1400px' },
      Fourx: { max: '410px' },
      Fourn: '410px',
      xxl: { min: '1600px' },
      xxls: { max: '1600px' },
      '6xl': { min: '1680px' },
      '6xls': { max: '1680px' },
      Mld: '521px',
      Mls: { max: '521px' },
      Msd: '576px',
      Mss: { max: '576px' },
      Mff: '1440px',
      Mffs: { max: '1440px' },
      sss: '380px',
      ssss: '321px',
      sssx: { max: '321px' },
      smj: { max: '990px' },
      smjs: { min: '990px' }
    },
  },
  plugins: [],
};
